name: Build and Push Docker Image

on:
  push:
    branches: [ anthropic-caching-dev ]
    paths:
      - 'packages/@n8n/nodes-langchain/**'
      - 'packages/nodes-base/**'
      - 'packages/core/**'
      - 'packages/workflow/**'
      - 'packages/cli/**'
      - 'docker/**'
      - 'Dockerfile'
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: tyop/n8n-anthropic-caching

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/images/n8n/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          N8N_VERSION=latest 